export const TABLE_CLIENTES = 'clientes';

export const COLUMNS_CLIENTES = [
  'CLIENTE_ID','NOMBRE','NIT','TELEFONO','TELEFONO_CELULAR','TELEFONO_REGISTRO','CORREO',
  'ZONA','CICLO','RUTA_REPARTO','RUTA_LECTURA','SECCION','ORDEN','MUNICIPIO','DESC_MUNICIPIO',
  'BARRIO','DIRECCION','CENTRO_POBLADO','FICHA_CATASTRAL','MATRICULA_INMOBILIARIA','ESTRATO',
  'CLASE_SERVICIO','NUMERO_MEDIDOR','MARCA_MEDIDOR','TECNOLOGIA_MEDIDOR','D_TECNOLOGIA_MEDIDOR',
  'TIPO_REGISTRADOR','D_TIPO_REGISTRADOR','UBICACION','GPS_LATITUD','GPS_LONGITUD','GPS_ALTITUD',
  'ESTADO_CLIENTE','TRANSFORMADOR','ALIMENTADOR','CODIGO_EXTERNO','COD_CIU'
];

export function buildInsertSQLClientes(batchLen) {
  const placeholdersOne = `(${COLUMNS_CLIENTES.map(() => '?').join(',')})`;
  const placeholdersAll = Array.from({ length: batchLen }).map(() => placeholdersOne).join(',');
  return `INSERT INTO ${TABLE_CLIENTES} (${COLUMNS_CLIENTES.join(',')}) VALUES ${placeholdersAll}`;
}